#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Invoke Drill using Java. Command line arguments are assumed to be
# of the form
#   -Dname=value
# and are passed to Java as JVM arguments.
#
# Environment Variables
#
#   DRILL_LOG_PREFIX        Path and name prefix for log files.
#                           (Set in drill-config.sh.)
#   DRILLBIT_LOG_PATH       Path to the Drillbit log file.
#                           (Set in drill-config.sh.)
#   DRILL_JAVA_OPTS         Optional JVM arguments such as system
#                           property overides used by both the
#                           drillbit (server) and client,
#                           set in drill-env.sh or the environment.
#   DRILLBIT_JAVA_OPTS      Optional JVM arguments specifically for
#                           the server (drillbit). Set in the
#                           environment or in the user defined
#                           drill-env.sh
#   SERVER_GC_OPTS          Set in drill-env.sh, customized by
#                           drillbit.sh.
#   CP                      Drillbit classpath set in drill-config.sh

cmd=$1
shift

drill_rotate_log ()
{
    log=$1;
    num=5;
    if [ -n "$2" ]; then
    num=$2
    fi
    if [ -f "$log" ]; then # rotate logs
    while [ $num -gt 1 ]; do
        prev=`expr $num - 1`
        [ -f "$log.$prev" ] && mv -f "$log.$prev" "$log.$num"
        num=$prev
    done
    mv -f "$log" "$log.$num";
    fi
}

if [ -n "$SERVER_GC_OPTS" ]; then
  loggc="${DRILL_LOG_PREFIX}.gc"
  export SERVER_GC_OPTS=${SERVER_GC_OPTS/"-Xloggc:<FILE-PATH>"/"-Xloggc:${loggc}"}
  drill_rotate_log $loggc
fi

export logqueries="${DRILL_LOG_PREFIX}_queries.json"
LOG_OPTS="-Dlog.path=$DRILLBIT_LOG_PATH -Dlog.query.path=$logqueries"
DRILL_ALL_JAVA_OPTS="$DRILLBIT_OPTS $DRILL_JAVA_OPTS $DRILLBIT_JAVA_OPTS $SERVER_GC_OPTS $@ $LOG_OPTS"
BITCMD="$JAVA $DRILL_ALL_JAVA_OPTS -cp $CP org.apache.drill.exec.server.Drillbit"

# Run the command (exec) or just print it (debug).
# Three options: run as a child (run), run & replace this process (exec) or
# just print the command (debug).

case $cmd in
(debug)
  echo "----------------- Environment ------------------"
  env
  echo "------------------------------------------------"
  echo "Launch command:"
  echo $BITCMD
  ;;
(*)
  exec $BITCMD
  ;;
esac
